name: Manual Publish (Twine)

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options: [testpypi, pypi]
        default: testpypi

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build

      - name: Upload with Twine (TestPyPI)
        if: ${{ inputs.target == 'testpypi' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Upload with Twine (PyPI)
        if: ${{ inputs.target == 'pypi' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
